### ISSUE TITLE
Support for pasting a url from the clipboard

### ISSUE THREAD

**Issue by ghost** [sagarchauhan005/chrome-bypass-paywall#2]
It would be a great option to be able to open a url from the clipboard rather than having to be on the page. Lots of sites redirect you to a "Pay for a subscription" page so you then cannot remove the paywall.

**Comment by sagarchauhan005** [comment]
Hey,

Thanks a lot for your suggestion. I shall try and implement this, over the coming weekend.

Will update you here, once I am done. Till then, please support my work if you can here (https://www.buymeacoffee.com/sagarchauhan005)

Regards
