### ISSUE TITLE
extension getting disabled

### ISSUE THREAD

**Issue by sasagr** [sagarchauhan005/chrome-bypass-paywall#3]
The extension is getting automatically disabled by Chrome every time I open the browser.

In the extension tabs I see the message "This extension violates the Chrome Web Store policy."
Any way to fix it?

**Comment by sagarchauhan005** [comment]
Hey, please read more about this here: https://postscripts.medium.com/bypass-paywall-so-this-happened-2e3de621335

**Comment by sasagr** [comment]
Hey. I just read it.
I see that I have installed the 0.0.3 while the latest seems to be the .4
However it does not look like the extension is hosted in chrome store anymore, as matter of fact if you browse:
https://chrome.google.com/webstore/detail/bypass/kkofljmpfaanangehehmbkkmbgjjlgja
you get an error
So at this point I m not sure I understand what are my options? apart from enabling it manually everytime

**Comment by sagarchauhan005** [comment]
Indeed, they started to remove the 0.0.3 version onwards, I tried to resubmit it as the 0.0.4 version with some changes but it was again taken down, so as a result, it's not longer hosted.

The only option for you or any user who has it already in their system is to keep it as it is, manually enables it, and never remove it, as you might not be able to install it again from the store.

Once removed, the only way to install would be to download from Github and install manually inside chrome

**Comment by sasagr** [comment]
sorry, one more question, is also the 0.0.4 being disabled automatically by Chrome?
I m considering to install manually the 0.0.4 on top of the 0.0.3 to avoid the automatic disabling.

**Comment by sagarchauhan005** [comment]
Hey @sasagr, all the versions are being disabled automatically, if you have enjoyed using the tools that I have built and especially this extension, consider buying me a coffee here https://www.buymeacoffee.com/sagarchauhan005.

You can also go ahead with Razorpay (UPI etc) if you are in India here https://pages.razorpay.com/sagarchauhan
