### ISSUE TITLE
Add a bypass for Patreon, SubscribeStar, SubscribeStar.adult, Pixiv Fanbox, Ko-Fi, Fantia, and Gumroad

### ISSUE THREAD

**Issue by golgon1995** [sagarchauhan005/chrome-bypass-paywall#4]
Can you please add a bypass for Patreon, SubscribeStar, SubscribeStar.adult, Pixiv Fanbox, Ko-Fi, Fantia, and Gumroad? We really need an extension to bypass/unblurr locked posts on Patreon, SubscribeStar, SubscribeStar.adult, Pixiv Fanbox, Ko-Fi, Fantia, and Gumroad.

**Comment by sagarchauhan005** [comment]
Hey, would be happy to work on it, if it is technically doable.

Can you share a locked post link to each one of the sites mentioned by you?

**Comment by golgon1995** [comment]
> Hey, would be happy to work on it, if it is technically doable.
> 
> Can you share a locked post link to each one of the sites mentioned by you?


I want EVERY locked post from Patreon, SubscribeStar, SubscribeStar.adult, Pixiv Fanbox, Ko-Fi, Fantia, and Gumroad to be un-blurred:

https://www.patreon.com/MAJUV

https://subscribestar.adult/paddedulf

https://pieceofsoap.fanbox.cc/posts

**Comment by sagarchauhan005** [comment]
Hey, I did not know these are adult links. Sorry, can't work on this. Marking this as closed.

**Comment by Obass-tech** [comment]
This guy just made others loose way too much potential things by posting his adults stuffs... mine is way too educational and I wish I could've got his chance before him.

**Comment by IoIxD** [comment]
Highly doubt it would've been possible anyways, I think this guy was talking out his a##.

These sites have been around for years, if it was currently possible there would be a site for it.

(and to be fair there is, its kemono.party, but be warned that it is mostly used for the adult content that this guy wanted and I've heard it's extremely spotty)

**Comment by Obass-tech** [comment]
Thank you but... I wasn't looking for things like those adults stuffs.

There are these Design presentations that I wanted to download, and as of I saw your post... I would really love if you can help me out.

They're packs of them.

In that site, I don't think if I may be able to find any of what I need as it's for adult things and I am not interested into that.

**Comment by Obass-tech** [comment]
I sent you a message in Instagram

@ obasskatule

**Comment by HTMedia8** [comment]
Can i please have a all of theses post unlocked and unblurred please also can i Have a Bypass for SubscribeStar Adult , Patreon ,Pixiv Fanbox and GumRoad Please

https://subscribestar.adult/nyankun


https://anymatickleterrorist.gumroad.com/l/EnigmaTerritoryTsGame

**Comment by Hbend712** [comment]
Hi there, I was wondering if you could just do Patreon, for it has some midis I want!

**Comment by DreamcastDude** [comment]
could you do this kofi link? i want this model https://ko-fi.com/summary/4ad3ad93-2a0f-4b22-9fc8-033de4286d92

**Comment by Peeksi** [comment]
can someone do this one?
https://ko-fi.com/s/fdd86325bc
my friend wants it for his birthday and i cant buy it myself :(

**Comment by 2dymbug** [comment]
https://ko-fi.com/s/59341bd334

**Comment by kalzomboid** [comment]
https://chambly.gumroad.com/l/SWGDSBB looking for this :(

**Comment by 123456789babygaminng** [comment]
https://ko-fi.com/texgon/shop     this plss

**Comment by xhshsww** [comment]
https://ko-fi.com/pigeonbasster/posts ,

**Comment by baldimore-ship-it** [comment]
https://ko-fi.com/s/71367299e6 this pls
